language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.16.0

before_install:
 - cd tetsujin
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - sudo pip install selenium
 - sudo pip install pymongo

script:
 - cd tetsujin
 - dotnet publish tetsujin.csproj -c Release -o ./obj/Docker/publish
 - docker build -t matoba/tetsujin:ci .
 - cd ..
 - mv -f docker-compose.travis.yml docker-compose.yml
 - rm docker-compose.override.yml
 - docker-compose config
 - docker-compose build
 - docker push matoba/tetsujin:ci
 - docker-compose up -d
 - cd ./SeleniumTest
 - python setup.py test
 - cd ..

after_success:
 - sh deploy.sh

matrix:
  fast_finish: true