language: python
python: 
  - "3.6" 

dist: xenial

addons:
  apt:
    sources:
      - docker-xenial
    packages:
      - gettext-base

before_install:
 # build environment
 - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
 - sudo dpkg -i packages-microsoft-prod.deb
 - sudo apt-get install apt-transport-https
 - sudo apt-get update
 - sudo apt-get install dotnet-sdk-2.2
 - dotnet --version
 - python --version
 - pip --version
 - docker -v
 - docker-compose -v
 # app
 - cd tetsujin
 - sudo -H pip install -r SeleniumTest/requirements.txt
 - sudo -H pip install -r PythonIntegtationTest/requirements.txt

script:
 - cd tetsujin
 - export BUILD_TIME=$(date '+%Y/%m/%d %R UTC')
 - envsubst '$$BUILD_TIME' < Dockerfile > _Dockerfile
 - cat _Dockerfile
 - dotnet publish tetsujin.csproj -c Release -o ./obj/Docker/publish
 - docker build -f _Dockerfile -t matoba/tetsujin:dev .
 - cd ..
 - docker-compose -f docker-compose.travis.yml config
 - docker-compose -f docker-compose.travis.yml build
 - docker-compose -f docker-compose.travis.yml up -d
 - sleep 10
 - docker ps -a
 - cd ./SeleniumTest
 - python setup.py test
 - cd ..
 - cd ./PythonIntegtationTest
 - python setup.py test
 - cd ..

after_success:
 - sh deploy.sh

matrix:
  fast_finish: true
