language: csharp
mono: none
dotnet: 2.1
dist: trusty
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - python3.6
        - python3-pip
        - gettext-base

before_install:
 - cd tetsujin
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - sudo -H pip3 install -r SeleniumTest/requirements.txt
 - sudo -H pip3 install -r PythonIntegtationTest/requirements.txt

script:
 - cd tetsujin
 - export BUILD_TIME=$(date '+%Y/%m/%d %R UTC')
 - envsubst '$$BUILD_TIME' < Dockerfile > _Dockerfile
 - cat _Dockerfile
 - dotnet publish tetsujin.csproj -c Release -o ./obj/Docker/publish
 - docker build -f _Dockerfile -t matoba/tetsujin:dev .
 - cd ..
 - docker-compose -f docker-compose.travis.yml config
 - docker-compose -f docker-compose.travis.yml build
 - docker-compose -f docker-compose.travis.yml up -d
 - sleep 10
 - docker ps -a
 - docker logs tetsujin_proxy_1
 - cd ./SeleniumTest
 - python3 setup.py test
 - cd ..
 - cd ./PythonIntegtationTest
 - python3 setup.py test
 - cd ..

after_success:
 - sh deploy.sh

matrix:
  fast_finish: true
