version: '3'

services:
  tetsujin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  ssldevenv:
    image: matoba/ssldevenv
    ports:
      - "443:443"
    links:
      - tetsujin:webapp