version: '3.4'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  proxy:
    image: matoba/ssldevenv:cc
    ports:
      - "443:443"
  selenium:
    image: selenium/standalone-chrome:3.12
    ports:
      - "4444:4444"