version: '3.4'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  proxy:
    image: matoba/ssldevenv
    ports:
      - "443:443"
  selenium:
    image: selenium/standalone-chrome:3.4
    ports:
      - "4444:4444"