version: '2'

services:
  webapp:
    image: matoba/tetsujin:ci
    environment:
      - HASHKEY=${HASHKEY}
      - MONGO_CONNECTION=mongodb://mymongo
      - STORAGE_ACCOUNT=XXX
      - STORAGE_KEY=XXX
      - STORAGE_URL=XXX
    links:
      - mymongo
  proxy:
    image: matoba/ssldevenv
    ports:
      - "443:443"
    links:
      - webapp
  selenium:
    image: selenium/standalone-chrome:3.4
    ports:
      - "4444:4444"
  mymongo:
    image: mongo
    ports:
      - "27017:27017"
