version: '3'

services:
  webapp:
    image: matoba/tetsujin:dev
    environment:
      - HASHKEY=${HASHKEY}
      - MONGO_CONNECTION=mongodb://mymongo
      - STORAGE_ACCOUNT=XXX
      - STORAGE_KEY=XXX
      - STORAGE_URL=XXX
    links:
      - mymongo
  proxy:
    image: matoba/ssldevenv:cc
    ports:
      - "443:443"
    environment:
      - LINK_TO=webapp
  selenium:
    image: selenium/standalone-chrome:3.12
    ports:
      - "4444:4444"
  mymongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
